version: "3"

services:
  postgres:
    image: postgres:10.12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hometime
      POSTGRES_DB: hometime_dev
      POSTGRES_PASSWORD: secret123
  hometime:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    links:
      - postgres
    environment:
      BUNDLE_PATH: /bundle/vendor
    env_file: .env

volumes:
  bundle:
  postgres:
